### ISSUE TITLE
Arduino编译不通过

### ISSUE THREAD

**Issue by qiuya90** [lewisxhe/ArduinoBIGIOT#3]
sketch\bigiot.cpp: In member function 'bool ServerChan::sendWechat(const char*, const char*)':

bigiot.cpp:617:19: error: exception handling disabled, use -fexceptions to enable

     } catch (std::bad_alloc) {

                   ^

exit status 1
exception handling disabled, use -fexceptions to enable

**Comment by lewisxhe** [comment]
> sketch\bigiot.cpp: In member function 'bool ServerChan::sendWechat(const char*, const char*)':
> 
> bigiot.cpp:617:19: error: exception handling disabled, use -fexceptions to enable
> 
> ```
>  } catch (std::bad_alloc) {
> 
>                ^
> ```
> exit status 1
> exception handling disabled, use -fexceptions to enable

请升级32编译工具链

**Comment by qiuya90** [comment]
> > sketch\bigiot.cpp: In member function 'bool ServerChan::sendWechat(const char*, const char*)':
> > bigiot.cpp:617:19: error: exception handling disabled, use -fexceptions to enable
> > ```
> >  } catch (std::bad_alloc) {
> > 
> >                ^
> > ```
> > exit status 1
> > exception handling disabled, use -fexceptions to enable
> 
> 请升级32编译工具链

感谢！我现在用的win平台，转到linux上面升级应该就好了。还有一个想请教，就是我想反馈led的结果，不论是建立client还是套用这段程序进行say，好像都无法反馈到贝壳，但是client换成自己建立的TCPserver地址和端口后都能发送到。不知道为何？后来我用在贝壳上添加一个设备，使client指向这个，也能发送到贝壳上。不知为何？是因为不允许同一设备收发？
改造了这段程序为say模式
String BIGIOT::getLoginPacket(String apiKey)
{
    String pack;
    jsonBuffer.clear();
    JsonObject &root = jsonBuffer.createObject();
    root["M"] = "checkin";   //改成了say
    root["ID"] = _dev;
    root["K"] = apiKey;     //改成了C
    root.printTo(pack);
    pack += "\n";
    DEBUG_BIGIOTCIENT("SEND LOGIN COMMAND:%s", pack.c_str());
    return pack;
}

**Comment by lewisxhe** [comment]
请参照贝壳通讯协议，贝壳没有反馈设备状态的接口，say只是用户与设备、设备与设备、用户与用户间沟通指令数据，参照贝壳协议第五条。

**Comment by qiuya90** [comment]
我指的是这种反馈。参展协议用模拟TCP完全ok，可esp8266不行。。。我用client接入贝壳的另一个设备接口，又可以反馈。就是不能在当前接口反馈。
![Uploading 捕获.JPG…]()

**Comment by qiuya90** [comment]
我指的是 https://www.bigiot.net/help/2.html 这种反馈LED on！参展协议用模拟TCP完全ok，可esp8266不行。。。我用client接入贝壳的另一个设备接口，又可以反馈。就是不能在当前接口反馈。

**Comment by lewisxhe** [comment]
> 我指的是 https://www.bigiot.net/help/2.html 这种反馈LED on！参展协议用模拟TCP完全ok，可esp8266不行。。。我用client接入贝壳的另一个设备接口，又可以反馈。就是不能在当前接口反馈。

这个我没加这个接口 ，我写这个库我自己本身并没使用贝壳这个平台，所以我并不知道需要哪些需求 ，需要你可以自己添加。

**Comment by qiuya90** [comment]
还想请教一下，我使用的是ESP8266，你之前说的“升级32编译工具链”能不能稍微指点一下？win平台下有吗？如何操作？谢谢

**Comment by lewisxhe** [comment]
@qiuya90 [参考](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/windows.md)
